#!/bin/bash
#Ver canales de televisión por streaming
CANALES="/home/$USER/.local/tv.mhyst/radio.conf"
#PLAYER="vlc -f --no-loop --play-and-exit"
PLAYER="mpv --fs"
VERSION="3.0.0"

function userChoice() {

    local limite=$1
    local cadena="$2"
    local reply
    let reply=0

    echo > /dev/tty
    echo "$cadena" > /dev/tty
    read reply < /dev/tty
    echo > /dev/tty

    #We see if the user entered a number such as we need
    while [[ "$reply" -lt 0 ]] || [[ "$reply" -gt  $limite ]]; do

    	#We give advice to the user and exit
	echo "Tiene que introducir un número de entre los indicados:" > /dev/tty
	read reply < /dev/tty
	#echo "Reply es: $reply" > /dev/tty

    done

    echo $reply
}

function getURL() {
    local canal="$1"
    
    local url="${canal##*|}"
    url=$(tr -d '\n' <<< "$url")
    echo "$url"
}

function getNombre() {
    local canal="$1"

    local nombre="${canal%|*}"
    echo "$nombre"
}

function checkConfig() {
    if ! [ -f "$CANALES" ]; then
	echo "Es la primera vez que ejecuta el script."
	echo "Se procederá a descargar el archivo de configuración:"
	mkdir /home/$USER/.local/tv.mhyst 2>&1
	wget -O "$CANALES" https://raw.githubusercontent.com/mhyst/spaintv/master/tv.conf 2>&1
    fi
}

echo "tv version $VERSION - Copyleft (GPL v3) Julio Serrano 2019"
echo "Ver televisión de España en streaming."
echo

checkConfig

readarray canales < "$CANALES"
if [[ ${#CANALES[@]} == 0 ]]; then
    echo "No hay canales!"
    echo
    echo "Por alguna razón no tiene canales en su fichero de configuración"
    echo "o no tiene archivo de configuración."
    echo
    echo "Aseguresé de tener conexión a internet la próxima vez que ejecute"
    echo "el script."
fi

# echo "Canales: ${#canales[@]}"

if [[ "$#" > 0 ]]; then
    cadena=${*,,}
    let i=0
    for canal in "${canales[@]}"; do
    	nombre=$(getNombre "$canal")
    	p="$nombre"
	s=${p,,}
	if [[ $s == *"$cadena"* ]]; then
	    chosen=$i
	    break
	fi
	(( i++ ))
    done

    if [[ $i == ${#canales[@]} ]]; then
	echo "No se ha encontrado ninguna cadena que coincida con \"$@\""
	exit
    fi
else
    let i=0
    echo "Estaciones de televisión"
    echo "------------------------"
    for canal in "${canales[@]}"; do
	echo "$i) $(getNombre "$canal")"
	(( i++ ))
    done

    limite=$(( ${#canales[@]} - 1 ))
    chosen=$(userChoice $limite "Seleccione la estación:")
fi

canal=${canales[$chosen]}
nombre=$(getNombre "$canal")
url=$(getURL "$canal")
echo "Ha elegido el canal $nombre"

if [ -f /tmp/tvpid ]; then
    tvpid=$(< /tmp/tvpid)
    #echo "tvpid: $tvpid"
    if [[ $tvpid != "" ]]; then 
	pcmd=$(ps -p $tvpid -o comm=)
	#Debug
	#echo "Comando: >$pcmd<"
	if [[ "$pcmd" == "vlc" ]] || [[ "$pcmd" == "mpv" ]]; then
	    echo "Matando el otro reproductor..."
	    kill -9 "$tvpid"
	fi
    fi
fi

echo "Reproduciendo"
${PLAYER} "$url" 2> /dev/null &
echo "$!" > /tmp/tvpid
